#ifndef EDGEML_ARDUINO_SENSORSCHEME_H
#define EDGEML_ARDUINO_SENSORSCHEME_H

// Device Data Types
#define PARSE_TYPE_UINT8 0
#define PARSE_TYPE_UINT16 1
#define PARSE_TYPE_UINT24 2
#define PARSE_TYPE_UINT32 3

#define PARSE_TYPE_INT8 4
#define PARSE_TYPE_INT16 5
#define PARSE_TYPE_INT24 6
#define PARSE_TYPE_INT32 7

#define PARSE_TYPE_FLOAT 8

// Device Schemes
#define SCHEME_VAL 0
#define SCHEME_DUAL_VAL 1
#define SCHEME_XYZ 2

#endif //EDGEML_ARDUINO_SENSORSCHEME_H
