#ifndef EDGEML_ARDUINO_SENSORSCHEME_H
#define EDGEML_ARDUINO_SENSORSCHEME_H

enum ParseScheme {
    SCHEME_VAL,
    SCHEME_DUAL_VAL,
    SCHEME_TRIPLE_VAL,
    SCHEME_QUAD_VAL,
    SCHEME_XYZ,
    SCHEME_RGB,
    SCHEME_ORIENTATION,
    SCHEME_QUATERNION
};

enum ParseType {
    PARSE_TYPE_INT8,
    PARSE_TYPE_UINT8,

    PARSE_TYPE_INT16,
    PARSE_TYPE_UINT16,

    PARSE_TYPE_INT24,
    PARSE_TYPE_UINT24,

    PARSE_TYPE_INT32,
    PARSE_TYPE_UINT32,

    PARSE_TYPE_FLOAT
};

#endif //EDGEML_ARDUINO_SENSORSCHEME_H
